### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by benjaminwinger** [UWARG/computer-vision#14]
I was thinking again about build systems. At the meeting today I mentioned that we should use make, though note that I actually meant to say CMake (a cross platform system which can generate makefiles for various systems such as GNU Make, Xcode or MS Visual Studio). 
An alternative would be to just use Make, which can run normally in OS X and through Cygwin on Windows. 

The other question I guess is what environment the end product will be running in. If we want to eventually run the program on a processor on the plane then the software will have to be able to run the program in Linux, however are we also going to use Linux on the Desktop for post-processing? For the past competition we had to use windows because we were using Microsoft ICE and Correlator3D for image stitching and volume calculation respectively, but if we end up having working in-house software for those purposes before the next competition then that will not be an issue.
If we end up just running the software in Linux, then targeting it specifically at Linux makes some sense, as we wouldn't have to worry about making everything cross-platform, but it may make things more frustrating for those of you who develop in Windows if you have to deal with everything through Cygwin (I think OS X handles Linux stuff better, but I'm not sure). Then again, I've never used Cygwin, so I don't really know.

Being someone who just uses Linux, I'm perfectly fine with targeting it solely at Linux, but what do the rest of you think?
In essence, CMake will allow for all development environments, but will require that we make a few sacrifices in implementation and would make the build system somewhat more complicated (it really only adds one more step to the build process though).

**Comment by CoatedMoose** [comment]
+1 for cmake. cmake, autotools and qmake all generate make files, which you then use to run make. I have the most experience with cmake though. 

Cygwin can be fine for the tool chain, buy doesn't give you much in terms of cross platform compatibility. See the what is(n't) cygwin on the front page of the cygwin website for more. 

All that said, unless there is a truely compelling reason, writing code in C/C++ to run on the ground station (or a Linux machine on the plane) is problematic. Development overhead is much greater for C/C++ as compared to something like java, python, other JVM languages, etc. Generally, the load intensive parts of these modules are going to be pushed off to native libraries, and we might as make the wrappers around them faster to write.

**Comment by mehatfie** [comment]
A little late here....but I think we should stick to C++ since we have already started it like that.
But Andrew has a point...writing this in Java would make it easier to deal with cross-platform. I think it is too late though.

For now lets target Linux. Worst case scenario, We will begin image stitching using Microsoft ICE when we restart the dual boot.

**Comment by chrishajduk84** [comment]
A little late here....but I think we should stick to C++ since we have already started it like that.
But Andrew has a point...writing this in Java would make it easier to deal with cross-platform. I think it is too late though.

For now lets target Linux. Worst case scenario, We will begin image stitching using Microsoft ICE when we restart the dual boot. We can also try Enblend, which is like Microsoft ICE but open source, and linux capable.
