### ISSUE TITLE
Unknown crash with input video and telemetry file

### ISSUE THREAD

**Issue by chrishajduk84** [UWARG/computer-vision#95]
![screenshot from 2018-01-14 17-55-56](https://user-images.githubusercontent.com/3022103/34921767-5d66caf8-f954-11e7-842c-bd8686c19806.png)
@benjaminwinger Would you have any idea why this happens? Is it the file format?

**Comment by chrishajduk84** [comment]
I can't seem to nail down where it happens, but I know it happens sometime after the "assign_workers" and "output" threads are queued. HOWEVER, it doesn't even start either one of the functions. So, sometime between when the workers are spawned and before each worker starts the process crashes.

Not quite sure...maybe there is a problem when instantiating certain objects???

**Comment by benjaminwinger** [comment]
That exception should probably be handled somewhere. It's thrown by either MetadataInput::get_metadata or MetadataInput::next_metadata, and it's probably due to the fact that VideoImport::next_frame doesn't have a try/catch around the get_metadata call like what PictureImport does.

As to why it's being thrown, I'm guessing that the formatting is different from what it's expecting. There should be errors logged though if that's the case. Is there anything even in the log file (which I think by default has log level of trace)?

**Comment by chrishajduk84** [comment]
Okay. That is possible.
I might have made a mistake creating the "test" csv file. I'll double check the columns.
I'll also add the try/catch block, and report back.
